import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { VoiceNoteItem } from '../types';

export const voiceNoteService = {
  async fetchVoiceNotes(): Promise<VoiceNoteItem[]> {
    if (!isSupabaseConfigured) return [];

    const { data, error } = await supabase
      .from('voice_notes')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) return [];

    return (data || []).map((row: any) => ({
      id: row.id,
      userId: row.user_id,
      title: row.title,
      duration: '0:45',
      transcript: row.transcript || 'Audio transcript generated by LifeVault Audio Engine.',
      createdAt: row.created_at,
      audioUrl: row.file_path,
    }));
  },

  async addVoiceNote(title: string, transcript: string, audioBlob?: Blob): Promise<VoiceNoteItem | null> {
    if (!isSupabaseConfigured) return null;

    const { data: userData } = await supabase.auth.getUser();
    if (!userData?.user) throw new Error('User authentication required.');

    let filePath: string | null = null;

    if (audioBlob) {
      const sanitized = `${Date.now()}_voice_memo.webm`;
      const path = `${userData.user.id}/${sanitized}`;
      await supabase.storage.from('voice-notes').upload(path, audioBlob, { upsert: true });
      const { data: urlData } = supabase.storage.from('voice-notes').getPublicUrl(path);
      filePath = urlData.publicUrl;
    }

    const payload = {
      user_id: userData.user.id,
      title,
      file_path: filePath,
      transcript,
    };

    const { data, error } = await supabase
      .from('voice_notes')
      .insert(payload)
      .select()
      .single();

    if (error) throw new Error(error.message);

    return {
      id: data.id,
      userId: data.user_id,
      title: data.title,
      duration: '0:30',
      transcript: data.transcript,
      createdAt: data.created_at,
      audioUrl: data.file_path,
    };
  },
};
